### ISSUE TITLE
400 error for /app endpoint after upgrade using proxy

### ISSUE THREAD

**Issue by smokedsalmonbagel** [sagemathinc/cocalc-docker#119]
I had cocalc deployed last year.  I pulled the new image and now I get '400 bad request' when requesting /app.  The interesting thing is index.html loads fine.  Here is my nginx config.  (I use it to provide our cert.)
```
access_log /dev/stdout;
error_log /dev/stdout debug;
server {
    listen 80;
    server_name cocalc.mydomain.org;
    server_tokens off;
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
       return 301 https://$host$request_uri;
    }
}

 map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
 }
server {
    listen 443 ssl;
    
    server_name cocalc.mydomain.org;
    
    ssl_certificate /etc/letsencrypt/live/cocalc.mydomain.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cocalc.mydomain.org/privkey.pem;

    location / {
        proxy_pass  https://cocalc:9090;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
		proxy_set_header Host $host;
    }  
}
```

Here is the cocalc service from docker-compose.yml
```
  cocalc:
    container_name: cocalc
    image: sagemathinc/cocalc
    restart: unless-stopped
    volumes:
      - /home/user/projects:/projects
    ports:
      - "9090:443"
    networks:
      - main
```
