### ISSUE TITLE
websocket closed every minute

### ISSUE THREAD

**Issue by webysther** [sagemathinc/cocalc-docker#194]
Hi, I started using this project in my NAS with docker compose and nginx proxy manager (fancy nginx) and I'm getting websocket drops, I have nearly 60 containers in my homelab and no issues, my configuration:

The ws primus close:

![image](https://github.com/sagemathinc/cocalc-docker/assets/750007/f7cc5cef-2c15-4e45-86d5-126340d5965a)

```yml
version: '3.9'

services:
  cocalc:
    image: sagemathinc/cocalc-v2
    container_name: app-calc
    env_file: ../cocalc/.env
    networks:
      cocalc:
    expose:
      - 80
    volumes:
      - /etc/TZ:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - "$STORAGE/projects:/projects"
    restart: unless-stopped

networks:
  cocalc:
    name: cocalc
```

```env
STORAGE=/volume1/docker/cocalc
NOSSL=true
```

My nginx is boring, websockets enabled and with cocalc resolving in the same bridge internally (look above the expose and not ports):

![image](https://github.com/sagemathinc/cocalc-docker/assets/750007/ccf2bf25-1bb7-4395-926b-974a1699cc53)

I'm using my public domain but the project is used as a personal tool, mainly to play around with jupyter.

![image](https://github.com/sagemathinc/cocalc-docker/assets/750007/c5f7d0e9-8eef-4b00-bd94-7e414e778351)

![image](https://github.com/sagemathinc/cocalc-docker/assets/750007/55628b30-11ce-4733-bd0e-cb888877d875)

![image](https://github.com/sagemathinc/cocalc-docker/assets/750007/dded08df-87fc-4743-99da-37259b5cdec2)

PS: No firewall rules from my pc to nas, cable connection, all wi-fi traffic is using another VLAN.
