### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by KenwoodFox** [sagemathinc/cocalc-docker#216]
Im seeing this and only this repeating every few seconds in my logs...

```
python3: error while loading shared libraries: /lib/x86_64-linux-gnu/libz.so.1: invalid ELF header
```

Fresh start, just trying to get going with CoCalc, what can I do to explore and figure out what im doing wrong?

```yaml
  cocalc:
    image: sagemathinc/cocalc-docker
    container_name: CoCalc
    restart: unless-stopped
    volumes:
     - /opt/cocalc/projects:/projects
    ports:
     - 4043:443
 ```

```
$ docker --version
Docker version 25.0.0, build e758fe5
```
