### ISSUE TITLE
provide docker-compose files

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [sagemathinc/cocalc-docker#66]
Instead of bundling everything, it's better to split the postgresql, haproxy and apache/nginx in separate containers from the rest.
This will allow to:

- let the user choose to use postgresql/haproxy from docker or from a socket

- automate letsencrypt certificate generation

Basically what I ask is to copy what's done with nextcloud here https://github.com/nextcloud/docker/tree/master/.examples

**Comment by TheFehr** [comment]
I'd love this. There is a lot of people (me included) who already have a reverse proxy setup (with traefik, caddy, nginx or something else) and for those a split up version would be amazing so that one can only start the parts that one need.

**Comment by Phlogi** [comment]
Here is a quick example using traefik as a reverse proxy: 

```
version: '3.6'
networks:
   proxy:
      external: true

services:
    cocalc:
        image: sagemathinc/cocalc
        restart: always
        container_name: cocalc
        networks:
          - proxy
        volumes:
            - /yourdata/cocalc/projects:/projects
        labels:
          - "traefik.enable=true"
          - "traefik.docker.network=proxy"
          - "traefik.http.routers.cocalc.rule=Host(`cocalc.yourdomain.test`)"
          - "traefik.http.routers.cocalc.tls.certresolver=le"
          - "traefik.http.routers.cocalc.service=cocalc"
# the port of cocal, does not allow insecured port 80 at the moment
# add:
# --
# serversTransport:
#  insecureSkipVerify: true
# --
# to your traefik config to allow invalid cert. 
          - "traefik.http.services.cocalc.loadbalancer.server.port=443"
# if you want to secure additionally with basic auth and have that setup in traefik
          - "traefik.http.routers.cocalc.entrypoints=websecure"
          - "traefik.http.routers.cocalc.middlewares=auth@file"
```

This uses the large cocalc image. If that image has one or multiple database servers, it should be split up. I didn't look into that yet.
